config/routes.rb
Rails.application.routes.draw do
  
  root 'tweets#index'
  
  devise_for :users
  resources :tweets

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	mount_uploader :photo_url, PhotoUploader
	belongs_to :user


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show] # user가 로그인 되어있는지 확인하라
    before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  def index
    # @tweets=Tweet.all
    # :id => :desc 를 줄여서 id: :desc
    @tweets = Tweet.order(id: :desc).page params[:page]
  end

  def edit
    set_tweet
  end

  def new
    @tweet=Tweet.new
  end

  def create
    # @tweet.new(
    #   title: params[:tweet][:title],
    #   content: params[:tweet][:content]
    # )
    Tweet.create(
      tweet_params
    )
    redirect_to tweets_path
  end

  def destroy
    set_tweet
    @tweet.destroy
    redirect_to tweets_path
  end

  def show
    set_tweet
  end

  def update
    set_tweet
    @tweet.update(
      tweet_params
    )
    redirect_to tweets_path
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params()
    params.require(:tweet).permit(:title,:content,:user_id,:photo_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FormFor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= link_to '홈으로', root_path%>
	<% if user_signed_in?%>
	<%= link_to '로그아웃', destroy_user_session_path, method: :delete%>
	<%= current_user.email%>님 환영합니다.
	<%else%>
	<%= link_to '로그인', new_user_session_path%>
	<%end%>

	<%= link_to '새 트윗쓰기',new_tweet_path%>

<p class="notice"><%= flash[:notice] %></p>
<p class="alert"><%= flash[:alert] %></p>
<%= yield %>

</body>
</html>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/destroy.html.erb
<h1>Tweets#destroy</h1>
<p>Find me in app/views/tweets/destroy.html.erb</p>

app/views/tweets/edit.html.erb
<h1>수정하기</h1>
<%= form_for(@tweet) do |f| %>
<p>제목:<%= f.text_field :title, placeholdeer:@tweet.title %></p>
<p>내용:<%= f.text_field :content, placeholdeer:@tweet.content %></p>

<p><%= f.submit "글쓰기"%></p>
<% end %>

app/views/tweets/index.html.erb
<h1>트윗 목록보기</h1>
<% @tweets.each do |t| %>
제목: <%= t.title%><br>
내용: <%= t.content %><br>
글쓴이 : <%= t.user.email if t.user %><br>

<% if t.photo_url.size > 2 %>
사진 : <%= image_tag "#{t.photo_url}",  height: '64', width: '64'  %><br>
<!-- <p><%= t.photo_url %></p> -->
<% end %>

<%= link_to "보기",tweet_path(t.id) %><br>
<%end%>
<%=link_to "글쓰기" ,new_tweet_path %>

<%= paginate @tweets %>

app/views/tweets/new.html.erb
<h1>글쓰기</h1>
<%= form_for(@tweet) do |f| %>
<p>제목:<%= f.text_field :title  %></p>
<p>내용:<%= f.text_field :content %></p>
<p>사진업로드 : <%= f.file_field :photo_url %></p>
<%= f.hidden_field :user_id, value: current_user.id%>
<p><%= f.submit "글쓰기"%></p>
<% end %>

app/views/tweets/show.html.erb
<h1>Tweet 내용보기</h1>
제목 : <%= @tweet.title%><br>
내용 : <%= @tweet.content %><br>
<%= link_to "수정",edit_tweet_path(@tweet) %> 
<%= link_to "삭제",tweet_path(@tweet),method: "delete" %>

app/views/tweets/update.html.erb
<h1>Tweets#update</h1>
<p>Find me in app/views/tweets/update.html.erb</p>